version: "3.9"
services:
  node:
    build: .
    volumes:
      - ./:/app
    working_dir: /app
    command: "node bin/www"
    restart: always
    depends_on:
      - browser
    ports:
      - "9001:9001"
    environment:
      BROWSER_URL: 'ws://browser:3000'
  # ...

  browser:
    image: browserless/chrome:1-chrome-stable
    hostname: browser
    volumes:
      - ./.wwebjs_auth/session-master/:/usr/src/app/user-data-dir
    environment:
      CONNECTION_TIMEOUT: -1
      KEEP_ALIVE: 'true'
      WORKSPACE_EXPIRE_DAYS: 1
      ENABLE_CORS: 'true'
      CHROME_REFRESH_TIME: 86400000
      DEFAULT_BLOCK_ADS: 'true'
      FUNCTION_ENABLE_INCOGNITO_MODE: 'true'
      ENABLE_XVBF: 'true'
      CHROME_PATH: '/usr/bin/google-chrome'
      USE_CHROME_STABLE: 'true'
      NODE_ENV: 'production'
      MAX_CONCURRENT_SESSIONS: 1
      DEFAULT_USER_DATA_DIR: /usr/src/app/user-data-dir
